## 1.1
#### <b> Hypothesis: </b> y_pred = mx +  b 
#### <b> Parameters : </b> m (coefficient,slope, gradient , weights) , b (Bias , intercept)

#### <b> Actual function : </b> y_actual= 2x + 1 
#### <b> Parameters : </b> 2 (coefficient,slope, gradient , weights) , 1 (Bias , intercept)

#### <b> Minimize :</b> the distance y_pred and y_actual 

## 1.2 
#### Lets create a data set 

In [1]:
x_values = [ i for i in range(11)]
x_values

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
import numpy as np 
x_train = np.array(x_values,dtype=np.float32)
x_train.shape

(11,)

In [3]:
# 2 d Array
x_train = x_train.reshape(11,1)
x_train.shape

(11, 1)

In [4]:
#### Actual function : y_actual= 2x + 1 
y_value = [ 2*i+1 for i in x_values]
y_value

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21]

In [7]:
y_train = np.array(y_value,dtype=np.float32)
y_train.shape

(11,)

In [8]:
y_train=y_train.reshape(11,1)
y_train.shape

(11, 1)

In [5]:
import torch
import torch.nn as nn ## require to build a linear regression model 
from torch.autograd import Variable

In [9]:
#Step 1 : Create a Model
#Building our Model
# Create class

class LinearRegressionModel(nn.Module):
    def __init__ (self,input_size,output_size):
        super().__init__()
        self.Linear = nn.Linear(input_dim,output_dim) # this means y=mx + 1 
        
    def forward(self,x):
        out = self.Linear(x)
        return out

In [10]:
## Step 2 :  Intantiate a model
input_dim = 1 
output_dim = 1 
model  = LinearRegressionModel(input_dim,output_dim)

In [11]:
## Step 3 : Intantiate a loss
criterion = nn.MSELoss()

In [12]:
## Step 4 : Intantiate a optimizer class : paramenets = parameters - learning_rate * parameter_gradients

learning_rate = 0.01
optimizer =  torch.optim.SGD(model.parameters(),learning_rate)

In [14]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4359]], requires_grad=True), Parameter containing:
 tensor([-0.2194], requires_grad=True)]

In [15]:
epochs = 100

In [27]:
# Step 5 : Train The model 
for epoch in range(epochs):
    epoch += 1 
    #convert numpy array to torch Variable
    inputs = Variable(torch.from_numpy(x_train))
    labels = Variable(torch.from_numpy(y_train))
    
    #clear the gradients 
    optimizer.zero_grad() # dont want to the gradients from previous epoch
    
    #get output 
    output = model(inputs)
    
    #calculate loss #scalar loss
    loss = criterion(output,labels)
    
    #getting gradients 
    loss.backward()
    
    #updating parameters 
    optimizer.step()
    
    print('epoch : {} ,  loss : {}'.format(epoch,loss))

epoch : 1 ,  loss : 7.979703514138237e-05
epoch : 2 ,  loss : 7.890591223258525e-05
epoch : 3 ,  loss : 7.802664185874164e-05
epoch : 4 ,  loss : 7.715288666076958e-05
epoch : 5 ,  loss : 7.628850289620459e-05
epoch : 6 ,  loss : 7.543867104686797e-05
epoch : 7 ,  loss : 7.459903281414881e-05
epoch : 8 ,  loss : 7.376360736088827e-05
epoch : 9 ,  loss : 7.294161332538351e-05
epoch : 10 ,  loss : 7.213030767161399e-05
epoch : 11 ,  loss : 7.132146129151806e-05
epoch : 12 ,  loss : 7.052611908875406e-05
epoch : 13 ,  loss : 6.973954441491514e-05
epoch : 14 ,  loss : 6.896247214172035e-05
epoch : 15 ,  loss : 6.818737892899662e-05
epoch : 16 ,  loss : 6.742563709849492e-05
epoch : 17 ,  loss : 6.667605339316651e-05
epoch : 18 ,  loss : 6.592811405425891e-05
epoch : 19 ,  loss : 6.519364251289517e-05
epoch : 20 ,  loss : 6.446345651056617e-05
epoch : 21 ,  loss : 6.374248914653435e-05
epoch : 22 ,  loss : 6.303205009317026e-05
epoch : 23 ,  loss : 6.232885789358988e-05
epoch : 24 ,  loss :

In [20]:
predicted = model(Variable(torch.from_numpy(x_train))).data.numpy()
predicted

array([[ 0.7231588],
       [ 2.7630265],
       [ 4.802894 ],
       [ 6.842762 ],
       [ 8.882629 ],
       [10.922497 ],
       [12.962365 ],
       [15.002233 ],
       [17.042099 ],
       [19.081966 ],
       [21.121834 ]], dtype=float32)

In [28]:
predicted = model(Variable(torch.from_numpy(x_train))).data.numpy()
predicted

array([[ 0.99046886],
       [ 2.9918413 ],
       [ 4.993214  ],
       [ 6.994587  ],
       [ 8.995959  ],
       [10.997332  ],
       [12.998705  ],
       [15.000077  ],
       [17.00145   ],
       [19.002823  ],
       [21.004194  ]], dtype=float32)

In [ ]:
y_train

In [ ]:
#save_model
save_model = False
if save_model is True :
    torch.save(model.state_dict(),'model_lr.pkl')

In [ ]:
#load_model
load_model = False
if load_model is True :
    torch.load_state_dict(torch.load('model_lr.pkl'))

In [21]:
list(model.parameters())

[Parameter containing:
 tensor([[2.0399]], requires_grad=True), Parameter containing:
 tensor([0.7232], requires_grad=True)]

In [29]:
list(model.parameters())

[Parameter containing:
 tensor([[2.0014]], requires_grad=True), Parameter containing:
 tensor([0.9905], requires_grad=True)]

In [ ]:
# Model and Variables on the GPU

In [ ]:
nn.Linear??